package send.point.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int PostWoman = 0;
  public static final int SendPoint = 1;
  public static final int SendPointAddress = 2;
  public static final int SendPointBody = 3;
  public static final int SendPointButton = 4;
  public static final int SendPointMethod = 5;
  public static final int SendPointParameter = 6;
  public static final int SendPointPathVariable = 7;
  public static final int SendPointResponseBody = 8;
  public static final int SendPointResponseStatus = 9;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0xd7b95e9eebcd4c13L, 0xb8b768e41a0acda9L);
    builder.put(0x1c579a248ea9a7bbL, PostWoman);
    builder.put(0x1c579a248ea9afaaL, SendPoint);
    builder.put(0xf4ef489a8cf7cf8L, SendPointAddress);
    builder.put(0xf4ef489a8cf812dL, SendPointBody);
    builder.put(0xf4ef489a8cf8505L, SendPointButton);
    builder.put(0xf4ef489a8cf8806L, SendPointMethod);
    builder.put(0xf4ef489a8cf8b2cL, SendPointParameter);
    builder.put(0xf4ef489a8cf9a37L, SendPointPathVariable);
    builder.put(0xf4ef489a8cf903cL, SendPointResponseBody);
    builder.put(0xf4ef489a8cf944cL, SendPointResponseStatus);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
