package send.point.sandbox;

/*Generated by MPS */

import javax.swing.JFrame;
import java.awt.GridLayout;
import javax.swing.SwingUtilities;

public class MyPostWoman extends JFrame {

  private PostExample sendPoint_a = new PostExample();
  private GetExample sendPoint_b = new GetExample();

  public MyPostWoman() {
    setTitle("PostWoman");
    setLayout(new GridLayout(0, 2));
    int size = 0;
    setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    add(sendPoint_a);
    size++;
    add(sendPoint_b);
    size++;
    if (size != 0) {
      setLayout(new GridLayout(0, size));
    }
    pack();
    setVisible(true);
  }

  public static void main(String[] args) {
    SwingUtilities.invokeLater(new Runnable() {
      @Override
      public void run() {
        new MyPostWoman();
      }
    });
  }

}
