package send.point.sandbox;

/*Generated by MPS */

import javax.swing.JPanel;
import javax.swing.event.DocumentListener;
import javax.swing.event.DocumentEvent;
import javax.swing.JTextField;
import javax.swing.JTextArea;
import javax.swing.JButton;
import javax.swing.JComboBox;
import java.io.IOException;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.URI;
import java.net.http.HttpResponse;
import java.awt.GridLayout;
import javax.swing.JLabel;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.BorderFactory;
import java.awt.Color;

public class Sendpoint4444 extends JPanel {

  private DocumentListener listener = new DocumentListener() {
    @Override
    public void insertUpdate(DocumentEvent p1) {
    }

    @Override
    public void removeUpdate(DocumentEvent p1) {
    }

    @Override
    public void changedUpdate(DocumentEvent p1) {
    }
  };
  private String[] methods = {"GET", "POST", "PUT", "DELETE"};
  private JTextField addressField_a = new JTextField();
  private JTextArea Sendpoint4444bodyField_a = new JTextArea();
  private JButton sendButton_a = new JButton("Send");
  private JComboBox method_a = new JComboBox<String>(methods);
  private JTextField responseStatus_a = new JTextField();
  private JTextArea responseBody_a = new JTextArea();

  private void send() throws IOException, InterruptedException {
    HttpClient client = HttpClient.newHttpClient();
    HttpRequest request = HttpRequest.newBuilder().GET().header("accept", "application/json").uri(URI.create("http://localhost:8080/testget")).build();
    HttpResponse<String> response = client.send(request, HttpResponse.BodyHandlers.ofString());
    System.out.println(response.body());
    System.out.println(response.statusCode());
  }

  public Sendpoint4444() {

    super(new GridLayout(0, 2));

    addressField_a.getDocument().addDocumentListener(listener);
    add(new JLabel("Address"));
    add(addressField_a);




    add(Sendpoint4444bodyField_a);

    sendButton_a.addActionListener(new ActionListener() {
      @Override
      public void actionPerformed(ActionEvent p1) {
        try {
          send();
        } catch (IOException | InterruptedException e) {
          System.out.println("blad");
        }
      }
    });
    add(sendButton_a);

    add(method_a);

    add(responseStatus_a);

    add(responseBody_a);


    super.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.BLACK), "  " + "SendPoint" + "   "));
  }
}
